/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssessmentQuestionsRouteImport } from './routes/assessment.questions'

const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentQuestionsRoute = AssessmentQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => AssessmentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRouteWithChildren
  '/assessment/questions': typeof AssessmentQuestionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRouteWithChildren
  '/assessment/questions': typeof AssessmentQuestionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRouteWithChildren
  '/assessment/questions': typeof AssessmentQuestionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/assessment' | '/assessment/questions'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/assessment' | '/assessment/questions'
  id: '__root__' | '/' | '/assessment' | '/assessment/questions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssessmentRoute: typeof AssessmentRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/questions': {
      id: '/assessment/questions'
      path: '/questions'
      fullPath: '/assessment/questions'
      preLoaderRoute: typeof AssessmentQuestionsRouteImport
      parentRoute: typeof AssessmentRoute
    }
  }
}

interface AssessmentRouteChildren {
  AssessmentQuestionsRoute: typeof AssessmentQuestionsRoute
}

const AssessmentRouteChildren: AssessmentRouteChildren = {
  AssessmentQuestionsRoute: AssessmentQuestionsRoute,
}

const AssessmentRouteWithChildren = AssessmentRoute._addFileChildren(
  AssessmentRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssessmentRoute: AssessmentRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
